// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb"

export default __t.row({
  id: __t.u64().primaryKey(),
  tenantSlug: __t.string().name("tenant_slug"),
  appName: __t.option(__t.string()).name("app_name"),
  appDescription: __t.option(__t.string()).name("app_description"),
  iconUrl: __t.option(__t.string()).name("icon_url"),
  iconVariantsJson: __t.option(__t.string()).name("icon_variants_json"),
  iconProvider: __t.option(__t.string()).name("icon_provider"),
  updatedAt: __t.timestamp().name("updated_at"),
})
