// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb"

export default __t.row({
  id: __t.u64().primaryKey(),
  namespace: __t.string(),
  key: __t.string(),
  contentType: __t.string().name("content_type"),
  data: __t.byteArray(),
  sizeBytes: __t.u32().name("size_bytes"),
  updatedAt: __t.timestamp().name("updated_at"),
  updatedByClerkUserId: __t.option(__t.string()).name("updated_by_clerk_user_id"),
})
