// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb"

export default __t.row({
  id: __t.u64().primaryKey(),
  navId: __t.string().name("nav_id"),
  parentNavId: __t.option(__t.string()).name("parent_nav_id"),
  scope: __t.string(),
  nodeType: __t.string().name("node_type"),
  label: __t.string(),
  sectionTitle: __t.option(__t.string()).name("section_title"),
  slugSegment: __t.option(__t.string()).name("slug_segment"),
  href: __t.option(__t.string()),
  iconName: __t.option(__t.string()).name("icon_name"),
  requiredRolesJson: __t.option(__t.string()).name("required_roles_json"),
  orderIndex: __t.u32().name("order_index"),
  alwaysVisible: __t.bool().name("always_visible"),
})
