// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb"

export default __t.row({
  id: __t.u64().primaryKey(),
  clerkUserId: __t.string().name("clerk_user_id"),
  avatarSeed: __t.option(__t.string()).name("avatar_seed"),
  chatbotAvatarSeed: __t.option(__t.string()).name("chatbot_avatar_seed"),
  chatbotTone: __t.option(__t.string()).name("chatbot_tone"),
  chatbotDetailLevel: __t.option(__t.string()).name("chatbot_detail_level"),
  chatbotEmojiUsage: __t.option(__t.string()).name("chatbot_emoji_usage"),
  updatedAt: __t.timestamp().name("updated_at"),
})
