// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb"

export default __t.row({
  id: __t.u64().primaryKey(),
  clerkUserId: __t.string().name("clerk_user_id"),
  email: __t.string(),
  displayName: __t.option(__t.string()).name("display_name"),
  avatarUrl: __t.option(__t.string()).name("avatar_url"),
  role: __t.string(),
  tenantId: __t.option(__t.u64()).name("tenant_id"),
  canSelectTheme: __t.bool().name("can_select_theme"),
  selectedTheme: __t.option(__t.string()).name("selected_theme"),
  colorScheme: __t.string().name("color_scheme"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
})
