// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb"

// Import all reducer arg schemas
import AppendChatMessageReducer from "./append_chat_message_reducer"
import CreateChatSessionReducer from "./create_chat_session_reducer"
import DeleteMembershipReducer from "./delete_membership_reducer"
import DeleteNavigationItemReducer from "./delete_navigation_item_reducer"
import DeleteRoleReducer from "./delete_role_reducer"
import DeleteThemeRegistryReducer from "./delete_theme_registry_reducer"
import DeleteUserByClerkIdReducer from "./delete_user_by_clerk_id_reducer"
import LogWebhookEventReducer from "./log_webhook_event_reducer"
import PublishInvalidationReducer from "./publish_invalidation_reducer"
import RecordAuditEventReducer from "./record_audit_event_reducer"
import RegisterServiceIdentityReducer from "./register_service_identity_reducer"
import UpdateUserProfileSettingsReducer from "./update_user_profile_settings_reducer"
import UpdateUserThemeStateReducer from "./update_user_theme_state_reducer"
import UpsertAppSettingsReducer from "./upsert_app_settings_reducer"
import UpsertMembershipReducer from "./upsert_membership_reducer"
import UpsertModulePermissionReducer from "./upsert_module_permission_reducer"
import UpsertNavigationItemReducer from "./upsert_navigation_item_reducer"
import UpsertRoleReducer from "./upsert_role_reducer"
import UpsertTenantReducer from "./upsert_tenant_reducer"
import UpsertThemeRegistryReducer from "./upsert_theme_registry_reducer"
import UpsertUserFromClerkReducer from "./upsert_user_from_clerk_reducer"
import UpsertWikiDocumentReducer from "./upsert_wiki_document_reducer"

// Import all procedure arg schemas
import * as GetAdminThemeProcedure from "./get_admin_theme_procedure"
import * as GetAppSettingsProcedure from "./get_app_settings_procedure"
import * as GetChatSessionOwnerProcedure from "./get_chat_session_owner_procedure"
import * as GetTenantIdByClerkOrgIdProcedure from "./get_tenant_id_by_clerk_org_id_procedure"
import * as GetThemeRegistryEntryProcedure from "./get_theme_registry_entry_procedure"
import * as GetUserByClerkIdProcedure from "./get_user_by_clerk_id_procedure"
import * as GetUserThemeStateProcedure from "./get_user_theme_state_procedure"
import * as GetWikiDocumentProcedure from "./get_wiki_document_procedure"
import * as ListChatMessagesProcedure from "./list_chat_messages_procedure"
import * as ListMembershipsProcedure from "./list_memberships_procedure"
import * as ListModulePermissionsProcedure from "./list_module_permissions_procedure"
import * as ListNavigationItemsProcedure from "./list_navigation_items_procedure"
import * as ListRolesProcedure from "./list_roles_procedure"
import * as ListTenantsProcedure from "./list_tenants_procedure"
import * as ListThemeRegistryProcedure from "./list_theme_registry_procedure"
import * as ListUsersProcedure from "./list_users_procedure"

// Import all table schema definitions
import InvalidationEventRow from "./invalidation_event_table"

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  invalidationEvent: __table(
    {
      name: "invalidation_event",
      indexes: [
        {
          accessor: "id",
          name: "invalidation_event_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
        {
          accessor: "invalidationEventTopic",
          name: "invalidation_event_topic_idx_btree",
          algorithm: "btree",
          columns: ["topic"],
        },
      ],
      constraints: [{ name: "invalidation_event_id_key", constraint: "unique", columns: ["id"] }],
    },
    InvalidationEventRow
  ),
})

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("append_chat_message", AppendChatMessageReducer),
  __reducerSchema("create_chat_session", CreateChatSessionReducer),
  __reducerSchema("delete_membership", DeleteMembershipReducer),
  __reducerSchema("delete_navigation_item", DeleteNavigationItemReducer),
  __reducerSchema("delete_role", DeleteRoleReducer),
  __reducerSchema("delete_theme_registry", DeleteThemeRegistryReducer),
  __reducerSchema("delete_user_by_clerk_id", DeleteUserByClerkIdReducer),
  __reducerSchema("log_webhook_event", LogWebhookEventReducer),
  __reducerSchema("publish_invalidation", PublishInvalidationReducer),
  __reducerSchema("record_audit_event", RecordAuditEventReducer),
  __reducerSchema("register_service_identity", RegisterServiceIdentityReducer),
  __reducerSchema("update_user_profile_settings", UpdateUserProfileSettingsReducer),
  __reducerSchema("update_user_theme_state", UpdateUserThemeStateReducer),
  __reducerSchema("upsert_app_settings", UpsertAppSettingsReducer),
  __reducerSchema("upsert_membership", UpsertMembershipReducer),
  __reducerSchema("upsert_module_permission", UpsertModulePermissionReducer),
  __reducerSchema("upsert_navigation_item", UpsertNavigationItemReducer),
  __reducerSchema("upsert_role", UpsertRoleReducer),
  __reducerSchema("upsert_tenant", UpsertTenantReducer),
  __reducerSchema("upsert_theme_registry", UpsertThemeRegistryReducer),
  __reducerSchema("upsert_user_from_clerk", UpsertUserFromClerkReducer),
  __reducerSchema("upsert_wiki_document", UpsertWikiDocumentReducer)
)

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema(
    "get_admin_theme",
    GetAdminThemeProcedure.params,
    GetAdminThemeProcedure.returnType
  ),
  __procedureSchema(
    "get_app_settings",
    GetAppSettingsProcedure.params,
    GetAppSettingsProcedure.returnType
  ),
  __procedureSchema(
    "get_chat_session_owner",
    GetChatSessionOwnerProcedure.params,
    GetChatSessionOwnerProcedure.returnType
  ),
  __procedureSchema(
    "get_tenant_id_by_clerk_org_id",
    GetTenantIdByClerkOrgIdProcedure.params,
    GetTenantIdByClerkOrgIdProcedure.returnType
  ),
  __procedureSchema(
    "get_theme_registry_entry",
    GetThemeRegistryEntryProcedure.params,
    GetThemeRegistryEntryProcedure.returnType
  ),
  __procedureSchema(
    "get_user_by_clerk_id",
    GetUserByClerkIdProcedure.params,
    GetUserByClerkIdProcedure.returnType
  ),
  __procedureSchema(
    "get_user_theme_state",
    GetUserThemeStateProcedure.params,
    GetUserThemeStateProcedure.returnType
  ),
  __procedureSchema(
    "get_wiki_document",
    GetWikiDocumentProcedure.params,
    GetWikiDocumentProcedure.returnType
  ),
  __procedureSchema(
    "list_chat_messages",
    ListChatMessagesProcedure.params,
    ListChatMessagesProcedure.returnType
  ),
  __procedureSchema(
    "list_memberships",
    ListMembershipsProcedure.params,
    ListMembershipsProcedure.returnType
  ),
  __procedureSchema(
    "list_module_permissions",
    ListModulePermissionsProcedure.params,
    ListModulePermissionsProcedure.returnType
  ),
  __procedureSchema(
    "list_navigation_items",
    ListNavigationItemsProcedure.params,
    ListNavigationItemsProcedure.returnType
  ),
  __procedureSchema("list_roles", ListRolesProcedure.params, ListRolesProcedure.returnType),
  __procedureSchema("list_tenants", ListTenantsProcedure.params, ListTenantsProcedure.returnType),
  __procedureSchema(
    "list_theme_registry",
    ListThemeRegistryProcedure.params,
    ListThemeRegistryProcedure.returnType
  ),
  __procedureSchema("list_users", ListUsersProcedure.params, ListUsersProcedure.returnType)
)

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(
  tablesSchema.schemaType
)

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers)

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(
      REMOTE_MODULE,
      (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config)
    )
  }

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this)
  }
}
