// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb"

export default __t.row({
  id: __t.u64().primaryKey(),
  moduleId: __t.string().name("module_id"),
  roleName: __t.string().name("role_name"),
  hasAccess: __t.bool().name("has_access"),
})
