// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb"

export default __t.row({
  id: __t.u64().primaryKey(),
  themeId: __t.string().name("theme_id"),
  name: __t.string(),
  description: __t.option(__t.string()),
  dynamicFontsJson: __t.option(__t.string()).name("dynamic_fonts_json"),
  isBuiltin: __t.bool().name("is_builtin"),
  cssAssetPath: __t.option(__t.string()).name("css_asset_path"),
  updatedAt: __t.timestamp().name("updated_at"),
})
