// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb"

export const AdminUserValue = __t.object("AdminUserValue", {
  id: __t.string(),
  clerkUserId: __t.string(),
  email: __t.string(),
  displayName: __t.option(__t.string()),
  role: __t.string(),
  createdAtMicros: __t.string(),
})
export type AdminUserValue = __Infer<typeof AdminUserValue>

export const AppSetting = __t.object("AppSetting", {
  id: __t.u64(),
  tenantSlug: __t.string(),
  appName: __t.option(__t.string()),
  appDescription: __t.option(__t.string()),
  iconUrl: __t.option(__t.string()),
  iconVariantsJson: __t.option(__t.string()),
  iconProvider: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
})
export type AppSetting = __Infer<typeof AppSetting>

export const AppSettingsValue = __t.object("AppSettingsValue", {
  tenantSlug: __t.string(),
  appName: __t.option(__t.string()),
  appDescription: __t.option(__t.string()),
  iconUrl: __t.option(__t.string()),
  iconVariantsJson: __t.option(__t.string()),
  iconProvider: __t.option(__t.string()),
})
export type AppSettingsValue = __Infer<typeof AppSettingsValue>

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sessionId: __t.u64(),
  authorType: __t.string(),
  content: __t.string(),
  toolName: __t.option(__t.string()),
  toolState: __t.option(__t.string()),
  createdAt: __t.timestamp(),
})
export type ChatMessage = __Infer<typeof ChatMessage>

export const ChatMessageValue = __t.object("ChatMessageValue", {
  id: __t.string(),
  sessionKey: __t.string(),
  authorType: __t.string(),
  content: __t.string(),
  toolName: __t.option(__t.string()),
  toolState: __t.option(__t.string()),
  createdAtMicros: __t.string(),
})
export type ChatMessageValue = __Infer<typeof ChatMessageValue>

export const ChatSession = __t.object("ChatSession", {
  id: __t.u64(),
  clerkUserId: __t.option(__t.string()),
  tenantSlug: __t.option(__t.string()),
  title: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
})
export type ChatSession = __Infer<typeof ChatSession>

export const ChatSessionAlias = __t.object("ChatSessionAlias", {
  id: __t.u64(),
  sessionKey: __t.string(),
  sessionId: __t.u64(),
  updatedAt: __t.timestamp(),
})
export type ChatSessionAlias = __Infer<typeof ChatSessionAlias>

export const CoreRole = __t.object("CoreRole", {
  id: __t.u64(),
  name: __t.string(),
  displayName: __t.option(__t.string()),
  description: __t.option(__t.string()),
  isSystem: __t.bool(),
})
export type CoreRole = __Infer<typeof CoreRole>

export const CoreUser = __t.object("CoreUser", {
  id: __t.u64(),
  clerkUserId: __t.string(),
  email: __t.string(),
  displayName: __t.option(__t.string()),
  avatarUrl: __t.option(__t.string()),
  role: __t.string(),
  tenantId: __t.option(__t.u64()),
  canSelectTheme: __t.bool(),
  selectedTheme: __t.option(__t.string()),
  colorScheme: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
})
export type CoreUser = __Infer<typeof CoreUser>

export const CoreUserPreference = __t.object("CoreUserPreference", {
  id: __t.u64(),
  clerkUserId: __t.string(),
  avatarSeed: __t.option(__t.string()),
  chatbotAvatarSeed: __t.option(__t.string()),
  chatbotTone: __t.option(__t.string()),
  chatbotDetailLevel: __t.option(__t.string()),
  chatbotEmojiUsage: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
})
export type CoreUserPreference = __Infer<typeof CoreUserPreference>

export const CoreUserProfileValue = __t.object("CoreUserProfileValue", {
  id: __t.string(),
  clerkUserId: __t.string(),
  email: __t.string(),
  displayName: __t.option(__t.string()),
  avatarUrl: __t.option(__t.string()),
  role: __t.string(),
  roleId: __t.option(__t.string()),
  tenantId: __t.option(__t.string()),
  canSelectTheme: __t.bool(),
  selectedTheme: __t.option(__t.string()),
  colorScheme: __t.string(),
  avatarSeed: __t.option(__t.string()),
  chatbotAvatarSeed: __t.option(__t.string()),
  chatbotTone: __t.option(__t.string()),
  chatbotDetailLevel: __t.option(__t.string()),
  chatbotEmojiUsage: __t.option(__t.string()),
})
export type CoreUserProfileValue = __Infer<typeof CoreUserProfileValue>

export const InvalidationEvent = __t.object("InvalidationEvent", {
  id: __t.u64(),
  topic: __t.string(),
  payloadJson: __t.option(__t.string()),
  createdAt: __t.timestamp(),
})
export type InvalidationEvent = __Infer<typeof InvalidationEvent>

export const Membership = __t.object("Membership", {
  id: __t.u64(),
  userId: __t.u64(),
  tenantId: __t.u64(),
  role: __t.string(),
  isActive: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
})
export type Membership = __Infer<typeof Membership>

export const MembershipValue = __t.object("MembershipValue", {
  userId: __t.string(),
  clerkUserId: __t.string(),
  tenantId: __t.string(),
  role: __t.string(),
  isActive: __t.bool(),
})
export type MembershipValue = __Infer<typeof MembershipValue>

export const ModulePermission = __t.object("ModulePermission", {
  id: __t.u64(),
  moduleId: __t.string(),
  roleName: __t.string(),
  hasAccess: __t.bool(),
})
export type ModulePermission = __Infer<typeof ModulePermission>

export const ModulePermissionValue = __t.object("ModulePermissionValue", {
  moduleId: __t.string(),
  roleName: __t.string(),
  hasAccess: __t.bool(),
})
export type ModulePermissionValue = __Infer<typeof ModulePermissionValue>

export const RoleDefinitionValue = __t.object("RoleDefinitionValue", {
  id: __t.string(),
  name: __t.string(),
  displayName: __t.option(__t.string()),
  description: __t.option(__t.string()),
  isSystem: __t.bool(),
})
export type RoleDefinitionValue = __Infer<typeof RoleDefinitionValue>

export const Tenant = __t.object("Tenant", {
  id: __t.u64(),
  clerkOrgId: __t.string(),
  slug: __t.string(),
  name: __t.string(),
})
export type Tenant = __Infer<typeof Tenant>

export const TenantValue = __t.object("TenantValue", {
  id: __t.string(),
  clerkOrgId: __t.string(),
  slug: __t.string(),
  name: __t.string(),
})
export type TenantValue = __Infer<typeof TenantValue>

export const ThemeRegistry = __t.object("ThemeRegistry", {
  id: __t.u64(),
  themeId: __t.string(),
  name: __t.string(),
  description: __t.option(__t.string()),
  dynamicFontsJson: __t.option(__t.string()),
  isBuiltin: __t.bool(),
  cssAssetPath: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
})
export type ThemeRegistry = __Infer<typeof ThemeRegistry>

export const ThemeRegistryValue = __t.object("ThemeRegistryValue", {
  themeId: __t.string(),
  name: __t.string(),
  description: __t.option(__t.string()),
  dynamicFontsJson: __t.option(__t.string()),
  isBuiltin: __t.bool(),
  cssAssetPath: __t.option(__t.string()),
})
export type ThemeRegistryValue = __Infer<typeof ThemeRegistryValue>

export const UserThemeStateValue = __t.object("UserThemeStateValue", {
  theme: __t.string(),
  colorScheme: __t.string(),
  canSelectTheme: __t.bool(),
  isAdmin: __t.bool(),
})
export type UserThemeStateValue = __Infer<typeof UserThemeStateValue>

export const WebhookEventLog = __t.object("WebhookEventLog", {
  id: __t.u64(),
  externalEventId: __t.string(),
  source: __t.string(),
  payloadJson: __t.string(),
  receivedAt: __t.timestamp(),
})
export type WebhookEventLog = __Infer<typeof WebhookEventLog>

export const WikiDocument = __t.object("WikiDocument", {
  id: __t.u64(),
  slug: __t.string(),
  content: __t.string(),
  updatedAt: __t.timestamp(),
})
export type WikiDocument = __Infer<typeof WikiDocument>

export const WikiDocumentValue = __t.object("WikiDocumentValue", {
  slug: __t.string(),
  content: __t.string(),
})
export type WikiDocumentValue = __Infer<typeof WikiDocumentValue>
