// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb"

export default {
  id: __t.string(),
  parentId: __t.option(__t.string()),
  scope: __t.string(),
  nodeType: __t.string(),
  label: __t.string(),
  sectionTitle: __t.option(__t.string()),
  slugSegment: __t.option(__t.string()),
  href: __t.option(__t.string()),
  iconName: __t.option(__t.string()),
  requiredRolesJson: __t.option(__t.string()),
  orderIndex: __t.u32(),
  alwaysVisible: __t.bool(),
}
