// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb"

// Import all procedure arg schemas
import * as GetAdminThemeProcedure from "../get_admin_theme_procedure"
import * as GetAppSettingsProcedure from "../get_app_settings_procedure"
import * as GetChatSessionOwnerProcedure from "../get_chat_session_owner_procedure"
import * as GetTenantIdByClerkOrgIdProcedure from "../get_tenant_id_by_clerk_org_id_procedure"
import * as GetThemeRegistryEntryProcedure from "../get_theme_registry_entry_procedure"
import * as GetUserByClerkIdProcedure from "../get_user_by_clerk_id_procedure"
import * as GetUserThemeStateProcedure from "../get_user_theme_state_procedure"
import * as GetWikiDocumentProcedure from "../get_wiki_document_procedure"
import * as ListChatMessagesProcedure from "../list_chat_messages_procedure"
import * as ListMembershipsProcedure from "../list_memberships_procedure"
import * as ListModulePermissionsProcedure from "../list_module_permissions_procedure"
import * as ListNavigationItemsProcedure from "../list_navigation_items_procedure"
import * as ListRolesProcedure from "../list_roles_procedure"
import * as ListTenantsProcedure from "../list_tenants_procedure"
import * as ListThemeRegistryProcedure from "../list_theme_registry_procedure"
import * as ListUsersProcedure from "../list_users_procedure"

export type GetAdminThemeArgs = __Infer<typeof GetAdminThemeProcedure.params>
export type GetAdminThemeResult = __Infer<typeof GetAdminThemeProcedure.returnType>
export type GetAppSettingsArgs = __Infer<typeof GetAppSettingsProcedure.params>
export type GetAppSettingsResult = __Infer<typeof GetAppSettingsProcedure.returnType>
export type GetChatSessionOwnerArgs = __Infer<typeof GetChatSessionOwnerProcedure.params>
export type GetChatSessionOwnerResult = __Infer<typeof GetChatSessionOwnerProcedure.returnType>
export type GetTenantIdByClerkOrgIdArgs = __Infer<typeof GetTenantIdByClerkOrgIdProcedure.params>
export type GetTenantIdByClerkOrgIdResult = __Infer<
  typeof GetTenantIdByClerkOrgIdProcedure.returnType
>
export type GetThemeRegistryEntryArgs = __Infer<typeof GetThemeRegistryEntryProcedure.params>
export type GetThemeRegistryEntryResult = __Infer<typeof GetThemeRegistryEntryProcedure.returnType>
export type GetUserByClerkIdArgs = __Infer<typeof GetUserByClerkIdProcedure.params>
export type GetUserByClerkIdResult = __Infer<typeof GetUserByClerkIdProcedure.returnType>
export type GetUserThemeStateArgs = __Infer<typeof GetUserThemeStateProcedure.params>
export type GetUserThemeStateResult = __Infer<typeof GetUserThemeStateProcedure.returnType>
export type GetWikiDocumentArgs = __Infer<typeof GetWikiDocumentProcedure.params>
export type GetWikiDocumentResult = __Infer<typeof GetWikiDocumentProcedure.returnType>
export type ListChatMessagesArgs = __Infer<typeof ListChatMessagesProcedure.params>
export type ListChatMessagesResult = __Infer<typeof ListChatMessagesProcedure.returnType>
export type ListMembershipsArgs = __Infer<typeof ListMembershipsProcedure.params>
export type ListMembershipsResult = __Infer<typeof ListMembershipsProcedure.returnType>
export type ListModulePermissionsArgs = __Infer<typeof ListModulePermissionsProcedure.params>
export type ListModulePermissionsResult = __Infer<typeof ListModulePermissionsProcedure.returnType>
export type ListNavigationItemsArgs = __Infer<typeof ListNavigationItemsProcedure.params>
export type ListNavigationItemsResult = __Infer<typeof ListNavigationItemsProcedure.returnType>
export type ListRolesArgs = __Infer<typeof ListRolesProcedure.params>
export type ListRolesResult = __Infer<typeof ListRolesProcedure.returnType>
export type ListTenantsArgs = __Infer<typeof ListTenantsProcedure.params>
export type ListTenantsResult = __Infer<typeof ListTenantsProcedure.returnType>
export type ListThemeRegistryArgs = __Infer<typeof ListThemeRegistryProcedure.params>
export type ListThemeRegistryResult = __Infer<typeof ListThemeRegistryProcedure.returnType>
export type ListUsersArgs = __Infer<typeof ListUsersProcedure.params>
export type ListUsersResult = __Infer<typeof ListUsersProcedure.returnType>
