// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb"

// Import all reducer arg schemas
import AppendChatMessageReducer from "../append_chat_message_reducer"
import CreateChatSessionReducer from "../create_chat_session_reducer"
import DeleteBlobAssetReducer from "../delete_blob_asset_reducer"
import DeleteMembershipReducer from "../delete_membership_reducer"
import DeleteNavigationItemReducer from "../delete_navigation_item_reducer"
import DeleteRoleReducer from "../delete_role_reducer"
import DeleteThemeRegistryReducer from "../delete_theme_registry_reducer"
import DeleteUserByClerkIdReducer from "../delete_user_by_clerk_id_reducer"
import LogWebhookEventReducer from "../log_webhook_event_reducer"
import OnConnectReducer from "../on_connect_reducer"
import OnDisconnectReducer from "../on_disconnect_reducer"
import PublishInvalidationReducer from "../publish_invalidation_reducer"
import RecordAuditEventReducer from "../record_audit_event_reducer"
import RegisterServiceIdentityReducer from "../register_service_identity_reducer"
import UpdateUserProfileSettingsReducer from "../update_user_profile_settings_reducer"
import UpdateUserThemeStateReducer from "../update_user_theme_state_reducer"
import UpsertAppSettingsReducer from "../upsert_app_settings_reducer"
import UpsertBlobAssetReducer from "../upsert_blob_asset_reducer"
import UpsertMembershipReducer from "../upsert_membership_reducer"
import UpsertModulePermissionReducer from "../upsert_module_permission_reducer"
import UpsertNavigationItemReducer from "../upsert_navigation_item_reducer"
import UpsertRoleReducer from "../upsert_role_reducer"
import UpsertTenantReducer from "../upsert_tenant_reducer"
import UpsertThemeRegistryReducer from "../upsert_theme_registry_reducer"
import UpsertUserFromClerkReducer from "../upsert_user_from_clerk_reducer"
import UpsertWikiDocumentReducer from "../upsert_wiki_document_reducer"

export type AppendChatMessageParams = __Infer<typeof AppendChatMessageReducer>
export type CreateChatSessionParams = __Infer<typeof CreateChatSessionReducer>
export type DeleteBlobAssetParams = __Infer<typeof DeleteBlobAssetReducer>
export type DeleteMembershipParams = __Infer<typeof DeleteMembershipReducer>
export type DeleteNavigationItemParams = __Infer<typeof DeleteNavigationItemReducer>
export type DeleteRoleParams = __Infer<typeof DeleteRoleReducer>
export type DeleteThemeRegistryParams = __Infer<typeof DeleteThemeRegistryReducer>
export type DeleteUserByClerkIdParams = __Infer<typeof DeleteUserByClerkIdReducer>
export type LogWebhookEventParams = __Infer<typeof LogWebhookEventReducer>
export type OnConnectParams = __Infer<typeof OnConnectReducer>
export type OnDisconnectParams = __Infer<typeof OnDisconnectReducer>
export type PublishInvalidationParams = __Infer<typeof PublishInvalidationReducer>
export type RecordAuditEventParams = __Infer<typeof RecordAuditEventReducer>
export type RegisterServiceIdentityParams = __Infer<typeof RegisterServiceIdentityReducer>
export type UpdateUserProfileSettingsParams = __Infer<typeof UpdateUserProfileSettingsReducer>
export type UpdateUserThemeStateParams = __Infer<typeof UpdateUserThemeStateReducer>
export type UpsertAppSettingsParams = __Infer<typeof UpsertAppSettingsReducer>
export type UpsertBlobAssetParams = __Infer<typeof UpsertBlobAssetReducer>
export type UpsertMembershipParams = __Infer<typeof UpsertMembershipReducer>
export type UpsertModulePermissionParams = __Infer<typeof UpsertModulePermissionReducer>
export type UpsertNavigationItemParams = __Infer<typeof UpsertNavigationItemReducer>
export type UpsertRoleParams = __Infer<typeof UpsertRoleReducer>
export type UpsertTenantParams = __Infer<typeof UpsertTenantReducer>
export type UpsertThemeRegistryParams = __Infer<typeof UpsertThemeRegistryReducer>
export type UpsertUserFromClerkParams = __Infer<typeof UpsertUserFromClerkReducer>
export type UpsertWikiDocumentParams = __Infer<typeof UpsertWikiDocumentReducer>
