#!/usr/bin/env tsx
/**
 * Build-Script: Generiert src/config/version.ts mit App-Version, Commit-SHA und Environment
 *
 * Wird vor jedem Build ausgeführt (prebuild hook).
 *
 * Logik:
 * - App-Version: Git-Tag vX.Y.Z -> X.Y.Z, Fallback: package.json.version, letzter Fallback: 0.0.0-dev
 * - Commit-SHA: VERCEL_GIT_COMMIT_SHA (8 Zeichen) oder git rev-parse --short HEAD
 * - Environment: VERCEL_ENV oder NODE_ENV -> development | preview | production
 */

import { execSync } from "node:child_process"
import { writeFileSync, mkdirSync } from "node:fs"
import { resolve } from "node:path"
import { readFileSync } from "node:fs"

/**
 * Liest Git-Tag des aktuellen Commits
 * @returns Tag-String (z.B. "v0.3.0") oder null wenn kein Tag
 */
function getGitTag(): string | null {
  try {
    const tag = execSync("git describe --tags --exact-match", {
      encoding: "utf8",
      stdio: "pipe",
    }).trim()
    return tag || null
  } catch {
    return null
  }
}

/**
 * Liest Version aus package.json
 * @returns Version-String (z.B. "0.1.0")
 */
function getPackageVersion(): string {
  try {
    const pkgPath = resolve(process.cwd(), "package.json")
    const pkgContent = readFileSync(pkgPath, "utf8")
    const pkg = JSON.parse(pkgContent) as { version?: string }
    return pkg.version ?? "0.0.0-dev"
  } catch {
    return "0.0.0-dev"
  }
}

/**
 * Liest Git Commit SHA
 * @returns Abgekürzte SHA (8 Zeichen) oder "unknown"
 */
function getGitSha(): string {
  // Vercel stellt VERCEL_GIT_COMMIT_SHA bereit
  const vercelSha = process.env.VERCEL_GIT_COMMIT_SHA
  if (vercelSha) {
    return vercelSha.slice(0, 8)
  }

  // Fallback: Lokale Git-SHA
  try {
    const sha = execSync("git rev-parse --short HEAD", {
      encoding: "utf8",
      stdio: "pipe",
    }).trim()
    return sha || "unknown"
  } catch {
    return "unknown"
  }
}

/**
 * Bestimmt Environment
 * @returns "development" | "preview" | "production"
 */
function getEnvironment(): "development" | "preview" | "production" {
  // Vercel stellt VERCEL_ENV bereit
  const vercelEnv = process.env.VERCEL_ENV
  if (vercelEnv === "production" || vercelEnv === "preview") {
    return vercelEnv
  }

  // Fallback: NODE_ENV
  const nodeEnv = process.env.NODE_ENV
  if (nodeEnv === "production") {
    return "production"
  }
  if (nodeEnv === "development") {
    return "development"
  }

  // Default: development
  return "development"
}

/**
 * Hauptfunktion: Generiert version.ts
 */
function main(): void {
  // 1. App-Version bestimmen
  const gitTag = getGitTag()
  let appVersion: string

  if (gitTag && gitTag.startsWith("v")) {
    // Git-Tag vorhanden: v0.3.0 -> 0.3.0
    appVersion = gitTag.slice(1)
  } else {
    // Fallback: package.json.version
    appVersion = getPackageVersion()
    // Wenn auch das fehlt, bleibt 0.0.0-dev (aus getPackageVersion)
  }

  // 2. Commit-SHA bestimmen
  const commitSha = getGitSha()

  // 3. Environment bestimmen
  const env = getEnvironment()

  // 4. TypeScript-Datei generieren
  const content = `// AUTO-GENERATED BY scripts/write-version.ts - DO NOT EDIT
// This file is regenerated on every build.

export const APP_VERSION = "${appVersion}" as const
export const APP_BUILD_COMMIT = "${commitSha}" as const
export const APP_ENV = "${env}" as const
`

  // 5. Verzeichnis erstellen falls nicht vorhanden
  const outDir = resolve(process.cwd(), "src/config")
  mkdirSync(outDir, { recursive: true })

  // 6. Datei schreiben
  const outFile = resolve(outDir, "version.ts")
  writeFileSync(outFile, content, "utf8")

  console.log(`✓ Generated ${outFile}`)
  console.log(`  APP_VERSION: ${appVersion}`)
  console.log(`  APP_BUILD_COMMIT: ${commitSha}`)
  console.log(`  APP_ENV: ${env}`)
}

main()
