import type { CoreNavigationRecord } from "@/lib/core"

/**
 * Statischer Seed fuer die erste Initialisierung der Core-Navigation.
 * Danach ist SpacetimeDB die produktive Source of Truth.
 *
 * WICHTIG: `as const satisfies readonly CoreNavigationRecord[]` — nur so bleiben die
 * String-Literals (`id`, `href`) fuer die TS-Gates in `hrefs.ts` erhalten
 * (sonst kollabiert `NavHref` zu `string`).
 */
export const NAVIGATION_SEED = [
  {
    id: "app-content",
    parentId: null,
    scope: "sidebar",
    nodeType: "section",
    label: "App Content",
    sectionTitle: "App Content",
    slugSegment: null,
    href: null,
    iconName: null,
    requiredRoles: [],
    orderIndex: 0,
    alwaysVisible: false,
  },
  {
    id: "module-1",
    parentId: "app-content",
    scope: "sidebar",
    nodeType: "group",
    label: "Modul 1",
    sectionTitle: null,
    slugSegment: "module-1",
    href: null,
    iconName: "FolderOpen",
    requiredRoles: [],
    orderIndex: 0,
    alwaysVisible: false,
  },
  {
    id: "module-1-1",
    parentId: "module-1",
    scope: "sidebar",
    nodeType: "page",
    label: "Sub-Modul 1.1",
    sectionTitle: null,
    slugSegment: "sub-1",
    href: "/module-1/sub-1",
    iconName: "FileText",
    requiredRoles: [],
    orderIndex: 0,
    alwaysVisible: false,
  },
  {
    id: "module-1-2",
    parentId: "module-1",
    scope: "sidebar",
    nodeType: "page",
    label: "Sub-Modul 1.2",
    sectionTitle: null,
    slugSegment: "sub-2",
    href: "/module-1/sub-2",
    iconName: "FileText",
    requiredRoles: [],
    orderIndex: 1,
    alwaysVisible: false,
  },
  {
    id: "module-1-3",
    parentId: "module-1",
    scope: "sidebar",
    nodeType: "page",
    label: "Sub-Modul 1.3",
    sectionTitle: null,
    slugSegment: "sub-3",
    href: "/module-1/sub-3",
    iconName: "FileText",
    requiredRoles: [],
    orderIndex: 2,
    alwaysVisible: false,
  },
  {
    id: "module-2",
    parentId: "app-content",
    scope: "sidebar",
    nodeType: "group",
    label: "Modul 2",
    sectionTitle: null,
    slugSegment: "module-2",
    href: null,
    iconName: "FolderOpen",
    requiredRoles: [],
    orderIndex: 1,
    alwaysVisible: false,
  },
  {
    id: "module-2-1",
    parentId: "module-2",
    scope: "sidebar",
    nodeType: "page",
    label: "Sub-Modul 2.1",
    sectionTitle: null,
    slugSegment: "sub-1",
    href: "/module-2/sub-1",
    iconName: "FileText",
    requiredRoles: [],
    orderIndex: 0,
    alwaysVisible: false,
  },
  {
    id: "module-2-2",
    parentId: "module-2",
    scope: "sidebar",
    nodeType: "page",
    label: "Sub-Modul 2.2",
    sectionTitle: null,
    slugSegment: "sub-2",
    href: "/module-2/sub-2",
    iconName: "FileText",
    requiredRoles: [],
    orderIndex: 1,
    alwaysVisible: false,
  },
  {
    id: "module-2-3",
    parentId: "module-2",
    scope: "sidebar",
    nodeType: "page",
    label: "Sub-Modul 2.3",
    sectionTitle: null,
    slugSegment: "sub-3",
    href: "/module-2/sub-3",
    iconName: "FileText",
    requiredRoles: [],
    orderIndex: 2,
    alwaysVisible: false,
  },
  {
    id: "module-3",
    parentId: "app-content",
    scope: "sidebar",
    nodeType: "group",
    label: "Modul 3",
    sectionTitle: null,
    slugSegment: "module-3",
    href: null,
    iconName: "FolderOpen",
    requiredRoles: [],
    orderIndex: 2,
    alwaysVisible: false,
  },
  {
    id: "module-3-1",
    parentId: "module-3",
    scope: "sidebar",
    nodeType: "page",
    label: "Sub-Modul 3.1",
    sectionTitle: null,
    slugSegment: "sub-1",
    href: "/module-3/sub-1",
    iconName: "FileText",
    requiredRoles: [],
    orderIndex: 0,
    alwaysVisible: false,
  },
  {
    id: "module-3-2",
    parentId: "module-3",
    scope: "sidebar",
    nodeType: "page",
    label: "Sub-Modul 3.2",
    sectionTitle: null,
    slugSegment: "sub-2",
    href: "/module-3/sub-2",
    iconName: "FileText",
    requiredRoles: [],
    orderIndex: 1,
    alwaysVisible: false,
  },
  {
    id: "module-3-3",
    parentId: "module-3",
    scope: "sidebar",
    nodeType: "page",
    label: "Sub-Modul 3.3",
    sectionTitle: null,
    slugSegment: "sub-3",
    href: "/module-3/sub-3",
    iconName: "FileText",
    requiredRoles: [],
    orderIndex: 2,
    alwaysVisible: false,
  },
  {
    id: "about",
    parentId: null,
    scope: "sidebar",
    nodeType: "section",
    label: "ÜBER DIE APP",
    sectionTitle: "ÜBER DIE APP",
    slugSegment: "ueber-die-app",
    href: "/ueber-die-app",
    iconName: null,
    requiredRoles: [],
    orderIndex: 1,
    alwaysVisible: false,
  },
  {
    id: "about-wiki",
    parentId: "about",
    scope: "sidebar",
    nodeType: "page",
    label: "App-Wiki",
    sectionTitle: null,
    slugSegment: "app-wiki",
    href: "/ueber-die-app/app-wiki",
    iconName: "BookOpen",
    requiredRoles: ["NoUser", "user", "admin"],
    orderIndex: 0,
    alwaysVisible: false,
  },
  {
    id: "about-features",
    parentId: "about",
    scope: "sidebar",
    nodeType: "page",
    label: "Feature-Wishlist",
    sectionTitle: null,
    slugSegment: "feature-wishlist",
    href: "/ueber-die-app/feature-wishlist",
    iconName: "Lightbulb",
    requiredRoles: ["user", "admin"],
    orderIndex: 1,
    alwaysVisible: false,
  },
  {
    id: "about-bugs",
    parentId: "about",
    scope: "sidebar",
    nodeType: "page",
    label: "Bug-Report",
    sectionTitle: null,
    slugSegment: "bug-report",
    href: "/ueber-die-app/bug-report",
    iconName: "Bug",
    requiredRoles: ["user", "admin"],
    orderIndex: 2,
    alwaysVisible: false,
  },
  {
    id: "about-impressum",
    parentId: "about",
    scope: "sidebar",
    nodeType: "page",
    label: "Impressum",
    sectionTitle: null,
    slugSegment: "impressum",
    href: "/ueber-die-app/impressum",
    iconName: "Mail",
    requiredRoles: ["NoUser", "user", "admin"],
    orderIndex: 3,
    alwaysVisible: true,
  },
  {
    id: "about-datenschutz",
    parentId: "about",
    scope: "sidebar",
    nodeType: "page",
    label: "Datenschutzerklärung",
    sectionTitle: null,
    slugSegment: "datenschutzerklaerung",
    href: "/ueber-die-app/datenschutzerklaerung",
    iconName: "ShieldCheck",
    requiredRoles: ["NoUser", "user", "admin"],
    orderIndex: 4,
    alwaysVisible: true,
  },
  {
    id: "admin",
    parentId: null,
    scope: "sidebar",
    nodeType: "section",
    label: "APP-VERWALTUNG",
    sectionTitle: "APP-VERWALTUNG",
    slugSegment: "app-verwaltung",
    href: "/app-verwaltung",
    iconName: null,
    requiredRoles: ["admin"],
    orderIndex: 2,
    alwaysVisible: false,
  },
  {
    id: "admin-dashboard",
    parentId: "admin",
    scope: "sidebar",
    nodeType: "page",
    label: "App-Dashboard",
    sectionTitle: null,
    slugSegment: "app-dashboard",
    href: "/app-verwaltung/app-dashboard",
    iconName: "Activity",
    requiredRoles: ["admin"],
    orderIndex: 0,
    alwaysVisible: false,
  },
  {
    id: "admin-app-logo",
    parentId: "admin",
    scope: "sidebar",
    nodeType: "page",
    label: "App-Logo",
    sectionTitle: null,
    slugSegment: "app-logo",
    href: "/app-verwaltung/app-logo",
    iconName: "Image",
    requiredRoles: ["admin"],
    orderIndex: 1,
    alwaysVisible: false,
  },
  {
    id: "admin-theme-manager",
    parentId: "admin",
    scope: "sidebar",
    nodeType: "page",
    label: "Theme Manager",
    sectionTitle: null,
    slugSegment: "theme-manager",
    href: "/app-verwaltung/theme-manager",
    iconName: "Palette",
    requiredRoles: ["admin"],
    orderIndex: 2,
    alwaysVisible: false,
  },
  {
    id: "admin-design-settings",
    parentId: "admin",
    scope: "sidebar",
    nodeType: "page",
    label: "Design System",
    sectionTitle: null,
    slugSegment: "design-system",
    href: "/app-verwaltung/design-system",
    iconName: "Paintbrush",
    requiredRoles: ["admin"],
    orderIndex: 3,
    alwaysVisible: false,
  },
  {
    id: "admin-components",
    parentId: "admin",
    scope: "sidebar",
    nodeType: "page",
    label: "UI-Komponenten",
    sectionTitle: null,
    slugSegment: "ui-komponenten",
    href: "/app-verwaltung/ui-komponenten",
    iconName: "Box",
    requiredRoles: ["admin"],
    orderIndex: 4,
    alwaysVisible: false,
  },
  {
    id: "admin-roles",
    parentId: "admin",
    scope: "sidebar",
    nodeType: "page",
    label: "Rollen",
    sectionTitle: null,
    slugSegment: "rollen",
    href: "/app-verwaltung/rollen",
    iconName: "Shield",
    requiredRoles: ["admin"],
    orderIndex: 5,
    alwaysVisible: false,
  },
  {
    id: "admin-users",
    parentId: "admin",
    scope: "sidebar",
    nodeType: "page",
    label: "Benutzer",
    sectionTitle: null,
    slugSegment: "benutzer",
    href: "/app-verwaltung/benutzer",
    iconName: "Users",
    requiredRoles: ["admin"],
    orderIndex: 6,
    alwaysVisible: false,
  },
  {
    id: "admin-datasources",
    parentId: "admin",
    scope: "sidebar",
    nodeType: "page",
    label: "Datenquellen",
    sectionTitle: null,
    slugSegment: "datenquellen",
    href: "/app-verwaltung/datenquellen",
    iconName: "Database",
    requiredRoles: ["admin"],
    orderIndex: 7,
    alwaysVisible: false,
  },
  {
    id: "admin-chat-logs",
    parentId: "admin",
    scope: "sidebar",
    nodeType: "page",
    label: "KI-Chat-Logs",
    sectionTitle: null,
    slugSegment: "ki-chat-logs",
    href: "/app-verwaltung/ki-chat-logs",
    iconName: "MessageSquare",
    requiredRoles: ["admin"],
    orderIndex: 8,
    alwaysVisible: false,
  },
  {
    id: "user-menu",
    parentId: null,
    scope: "user",
    nodeType: "section",
    label: "BENUTZER-MENÜ",
    sectionTitle: "BENUTZER-MENÜ",
    slugSegment: "benutzer-menue",
    href: "/benutzer-menue",
    iconName: null,
    requiredRoles: [],
    orderIndex: 0,
    alwaysVisible: false,
  },
  {
    id: "user-profile",
    parentId: "user-menu",
    scope: "user",
    nodeType: "page",
    label: "Profil",
    sectionTitle: null,
    slugSegment: "profil",
    href: "/benutzer-menue/profil",
    iconName: "User",
    requiredRoles: ["user", "admin"],
    orderIndex: 0,
    alwaysVisible: true,
  },
  {
    id: "user-cart",
    parentId: "user-menu",
    scope: "user",
    nodeType: "page",
    label: "Warenkorb",
    sectionTitle: null,
    slugSegment: "warenkorb",
    href: "/benutzer-menue/warenkorb",
    iconName: "ShoppingCart",
    requiredRoles: ["user", "admin"],
    orderIndex: 1,
    alwaysVisible: false,
  },
  {
    id: "user-language",
    parentId: "user-menu",
    scope: "user",
    nodeType: "page",
    label: "Sprache",
    sectionTitle: null,
    slugSegment: "sprache",
    href: "/benutzer-menue/sprache",
    iconName: "Languages",
    requiredRoles: ["user", "admin"],
    orderIndex: 3,
    alwaysVisible: false,
  },
  {
    id: "user-logout",
    parentId: "user-menu",
    scope: "user",
    nodeType: "action",
    label: "Abmelden",
    sectionTitle: null,
    slugSegment: null,
    href: null,
    iconName: "LogOut",
    requiredRoles: ["user", "admin"],
    orderIndex: 4,
    alwaysVisible: true,
  },
] as const satisfies readonly CoreNavigationRecord[]
